apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acs-securedcluster-helm
  namespace: stackrox
  annotations:
    policy.open-cluster-management.io/categories: Operators-Config
    policy.open-cluster-management.io/controls: ACS-Operator
    policy.open-cluster-management.io/standards: TofuOrg-Standards
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-namespace-charts
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: rhacs-charts-ns
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-securedcluster-helm-placementrule
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1
                kind: PlacementRule
                metadata:
                  name: acs-securedcluster-helm
                  namespace: stackrox
                  labels:
                    app: stackrox
                spec:
                  clusterSelector:
                    matchLabels:
                      eks: "true"
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-securedcluster-helm-application
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: app.k8s.io/v1beta1
                kind: Application
                metadata:
                  name: rhacs-securedcluster-helm
                  namespace: stackrox
                spec:
                  componentKinds:
                    - group: apps.open-cluster-management.io
                      kind: Subscription
                  descriptor: {}
                  selector:
                    matchLabels:
                      app: stackrox-secured-cluster-services
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-securedcluster-helm-channel
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1
                kind: Channel
                metadata:
                  name: rhacs-charts
                  namespace: rhacs-charts-ns
                  annotations:
                    apps.open-cluster-management.io/reconcile-rate: medium
                spec:
                  pathname: https://mirror.openshift.com/pub/rhacs/charts
                  type: HelmRepo
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-securedcluster-helm-subscription
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1
                kind: Subscription
                metadata:
                  name: stackrox-secured-cluster-services
                  namespace: stackrox
                  annotations:
                  labels:
                    app: stackrox-secured-cluster-services
                spec:
                  name: stackrox-secured-cluster-services
                  channel: rhacs-charts-ns/rhacs-charts
                  packageOverrides:
                    - packageAlias: stackrox-secured-cluster-svcs
                      packageName: stackrox-secured-cluster-services
                      packageOverrides:
                      - path: spec
                        value:
                          admissionControl:
                            serviceTLS:
                              cert: |
                                {{hub (index (lookup "v1" "Secret" "stackrox"
                                "admission-control-tls").data
                                "admission-control-cert.pem") | base64dec |
                                indent 18 hub}}
                              key: >
                                {{hub (index (lookup "v1" "Secret" "stackrox"
                                "admission-control-tls").data
                                "admission-control-key.pem") | base64dec |
                                indent 18 hub}}
                          allowNonstandardReleaseName: true
                          ca:
                            cert: >
                              {{hub (index (lookup "v1" "Secret" "stackrox"
                              "admission-control-tls").data "ca.pem") |
                              base64dec | indent 16 hub}}
                          centralEndpoint: '{{hub (lookup "route.openshift.io/v1" "Route" "stackrox"
                            "central").spec.host hub}}:443'
                          clusterName: |
                            {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
                          collector:
                            serviceTLS:
                              cert: >
                                {{hub (index (lookup "v1" "Secret" "stackrox"
                                "collector-tls").data "collector-cert.pem") |
                                base64dec | indent 18 hub}}
                              key: >
                                {{hub (index (lookup "v1" "Secret" "stackrox"
                                "collector-tls").data "collector-key.pem") |
                                base64dec | indent 18 hub}}
                          imagePullSecrets:
                            useExisting: pull-secret
                          sensor:
                            serviceTLS:
                              cert: >
                                {{hub (index (lookup "v1" "Secret" "stackrox"
                                "sensor-tls").data "sensor-cert.pem") |
                                base64dec | indent 18 hub}}
                              key: >
                                {{hub (index (lookup "v1" "Secret" "stackrox"
                                "sensor-tls").data "sensor-key.pem") |
                                base64dec | indent 18 hub}}
                  placement:
                    placementRef:
                      name: acs-securedcluster-helm
                      kind: PlacementRule
          remediationAction: enforce
          severity: high
  remediationAction: enforce
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-acs-securedcluster-helm
  namespace: stackrox
  annotations:
  labels:
    app: acs
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: eks
        operator: In
        values:
          - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-acs-securedcluster-helm
  namespace: stackrox
placementRef:
  name: placement-policy-acs-securedcluster-helm
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-acs-securedcluster-helm
    apiGroup: policy.open-cluster-management.io
    kind: Policy

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: acs
  name: placement-policy-acs-securedcluster-helm-sub
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: eks
      operator: In
      values:
      - 'true'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-acs-securedcluster-helm-sub

placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-policy-acs-securedcluster-helm-sub

subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-acs-securedcluster-helm-sub
